sudo: required

services:
  - docker

before_install:
  - docker pull asciidoctor/docker-asciidoctor

script:
  - docker run -v $TRAVIS_BUILD_DIR:/documents/ --name asciidoc-to-html asciidoctor/docker-asciidoctor /documents/build.sh

after_error:
  - docker logs asciidoc-to-html

after_failure:
  - docker logs asciidoc-to-html

deploy:
  provider: pages
  local-dir: site
  target-branch: gh-pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master
